name: Client CI

on: [push]

jobs:
  client_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: client
        run: npm ci

      - name: Build
        working-directory: client
        run: npm run build

      - name: Check formatting
        working-directory: client
        run: npm run format-check

      - name: Run linter
        working-directory: client
        run: npm run lint
